### ISSUE TITLE
DCO bot stuck in weird state.

### ISSUE THREAD

**Issue by JPWKU** [probot/dco#101]
Hi, It looks like the DCO check is in a weird state and not reporting.  Can you help us out or point out if we are doing something wrong here?  Thanks!
https://github.com/edgexfoundry/developer-scripts/pull/98

**Comment by JPWKU** [comment]
@hiimbex You helped us out last time, can you provide some direction here for us?

**Comment by hiimbex** [comment]
@JPWKU I see you closed and re-opened the PR which is definitely a good option. If the bot hangs, it might have either not been running or had some downtime? I no longer have access to the app's deployment logs (it's hosted on GitHub's Heroku enterprise account and I left GitHub)

But generally, the bot is triggered on a pull request being opened or "synchronized" which is any commits being pushed (including force pushed). So you can either open a new PR with the same commit, or force push the same commit on the same PR to trigger a new bot run. There's no real easy way to go through the webhook logs from our end and rerun a specific PR unfortunately.
