### ISSUE TITLE
Weird failure message

### ISSUE THREAD

**Issue by pombredanne** [probot/dco#110]
See https://github.com/nexB/deltacode/pull/114/checks?check_run_id=83064273
```
Commit sha: 18ec9a6, Author: Shubham, Committer: Shubham; Expected "Shubham shubhamsangamnerkar9@gmail.com", but got "Shubham shubhamsangamnerkar9@gmail.com".
```
The expected and got are exactly the same, so what is the catch?

**Comment by hiimbex** [comment]
There appears to me to be an extra space but that shouldn't cause a mismatch. Unsure the issue, but if you figure it out, PRs welcome

**Comment by pombredanne** [comment]
@hiimbex Thank you for the reply! 

> There appears to me to be an extra space but that shouldn't cause a mismatch. 

I could not find this extra space?

**Comment by hiimbex** [comment]
<img width="567" alt="Screen Shot 2019-04-19 at 1 27 40 PM" src="https://user-images.githubusercontent.com/13410355/56435576-ef46d280-62a6-11e9-8f1d-d8b7903642f0.png">

I'm highlighting a single space here, but, again, I don't think that should be an issue.
