### ISSUE TITLE
DCO indicates missing mismatch where there is none

### ISSUE THREAD

**Issue by timbms** [probot/dco#112]
I get the following feedback from DCO:

Commit sha: 96310b2, Author: Tim Müller-Seydlitz, Committer: Tim Müller-Seydlitz; Expected "Tim Müller-Seydlitz timbms@gmail.com", but got "Tim Müller-Seydlitz timbms@gmail.com".

Are "ü" and hyphenated names not properly treated?

**Comment by hiimbex** [comment]
It's entirely possible. I tried to recreate this unsuccessfully - linking to the PR could help me troubleshoot. PRs welcome though!

**Comment by timbms** [comment]
> It's entirely possible. I tried to recreate this unsuccessfully - linking to the PR could help me troubleshoot. PRs welcome though!

As soon as I make a new PR with the issue on openhab-ios I will let you know
