### ISSUE TITLE
DCO check fail when commit comes thru GH UI and committer email is set to private

### ISSUE THREAD

**Issue by jmertic** [probot/dco#114]
See this PR failure...

https://github.com/zowe/zlc/pull/114/checks?check_run_id=137885176

It looks like while the user put in their normal Signed-off-by: in the commit, because they have a GitHub setting on which doesn't pass their real email as the committer ( https://help.github.com/en/articles/about-commit-email-addresses ) we get a mismatch.

Any ideas on what could be done to solve this?

**Comment by hiimbex** [comment]
I think the fix here has to be on the user's end. They can either set their email to public or do as GitHub recommends:

> To use your noreply email address for commits you push from the command line, use that email address when you set your commit email address in Git.
