### ISSUE TITLE
There should be a blacklist option

### ISSUE THREAD

**Issue by tykeal** [probot/dco#118]
It would be very nice to have a blacklist option instead of just an 'All repositories' or 'Whitelist' option.

In general we prefer to just enable the DCO check on all repositories, and not have to worry about it for any new repositories that may be created later. We do, however, have some organizations that have need of disabling the bot on some repos and this make management of the organization significantly more difficult as we now have to remember to enable the bot on new repos.

With a blacklist option then any repo that doesn't require DCO can be configured to not have it and all new repos by default would have it enabled unless we determine later that it's not needed.

**Comment by hiimbex** [comment]
This is a limitation of GitHub Apps themselves, not specifically DCO, this does seem like a good feature request that could help lots of apps. Maybe you could send this feedback to GitHub support.
