### ISSUE TITLE
Merge blocked even though all commits are signed

### ISSUE THREAD

**Issue by Karsten1987** [probot/dco#123]
We are currently expiring something strange on the DCO bot we've applied to our repo. Even though all commits are signed and the DCO bot seems to return successfully from its checks, the "merge" buttons stays blocked.
 The PR in question: https://github.com/ros2/rmw_iceoryx/pull/7

Any idea on what's happening here? Are we doing something wrong?

I am attaching a screenshot of this as well for future references (the PR might get merged soonish):
<img width="763" alt="Screen Shot 2019-12-13 at 10 55 17 AM" src="https://user-images.githubusercontent.com/5419873/70824458-2d918480-1d97-11ea-979e-40329d37931a.png">

**Comment by hiimbex** [comment]
This is not related to the DCO.

In your branch protection settings do you have this checked?
<img width="409" alt="Screen Shot 2019-12-13 at 11 00 42 AM" src="https://user-images.githubusercontent.com/13410355/70824808-dfc94c00-1d97-11ea-8dd5-4ec4c101be7c.png">

If yes, see the article GitHub conveniently linked for you: https://help.github.com/en/github/authenticating-to-github/about-commit-signature-verification 

This person has signed off the DCO, but has not used a GPG key to sign their commit/s. Your repo currently enforces both.

**Comment by Karsten1987** [comment]
Thanks a lot for the explanation. That's exactly what was happening!
