### ISSUE TITLE
DCO bot is stuck in "Waiting for status to be reported"

### ISSUE THREAD

**Issue by fdw** [probot/dco#124]
Today, a lot of PRs came in from Dependabot. Unfortunately, none of them have been approved by the DCO bot.

After reading through #69 and #111, I tried to force push one branch and get DCO bot to react, but that didn't help. Any other ideas?

PS: Thanks for the work! You have no idea how much work and headache you saved us :)

**Comment by hiimbex** [comment]
Hey sorry for the delay in response, is this still happening?

Usually if it's a blip, a force push or additional commit can trigger the bot to try to run again. You can always wait a few hours and try that agin as well.

**Comment by fdw** [comment]
I did try a force push (IIRC), but that didn't help. Anyway, it's been working again, so no worries :)
