### ISSUE TITLE
Commit from PR UI Suggested Change

### ISSUE THREAD

**Issue by dfreilich** [probot/dco#128]
Hi! I tried to commit a suggestion from Github's PR UI, adding a DCO line on the bottom of the commit, but it didn't seem to work. 
![Screen Shot 2020-06-03 at 11 00 10 AM](https://user-images.githubusercontent.com/7035673/83653332-a4ab1700-a589-11ea-9479-2162a91e2b46.png)

Is there any way to commit a suggestion from Github's PR UI that will add a valid DCO line?

**Comment by jromero** [comment]
I wonder if it was due to it missing the `<` and `>` characters around the symbol? The check outcome is gone. :(

**Comment by dfreilich** [comment]
Ah perhaps somehow the brackets were stripped from it when I submitted it. I'll try again when given an opportunity to see if it's possible

**Comment by dfreilich** [comment]
I got it to successfully work when I added in the brackets.
