### ISSUE TITLE
Please don't check signoffs on merge commits

### ISSUE THREAD

**Issue by dankohn** [probot/dco#13]
Hi, https://github.com/coreinfrastructure/best-practices-badge is a happy user of your DCObot. The issue is that there is no `--signoff` option in git for merge commits, which is a standard part of our workflow with feature branches. Here is a workflow where we currently get stuck:
```sh
(master)$ git checkout -b feature-branch
# make some changes
(feature-branch)$ git commit -sam 'Adding features'
# Changes have occurred on master so need to add them for easier merge
(feature-branch)$ git fetch
(feature-branch)$ git merge origin/master
# Save default commit message
(feature-branch)$ git push
# This now fails the DCObot check because the merge commit is not signed.
```
This alternative workflow works, but is obviously tedious:
```sh
# First 3 steps are the same
(feature-branch)$ git merge origin/master
# Save default commit message
(feature-branch)$ git commit --amend -s
# Commit message now has signoff line
(feature-branch)$ git push
# This now passes the DCObot check.
```
Or, I could manually add the Signoff line to the proposed git merge commit message, which would allow me to skip the `--amend` step.

Could you please add an option to the DCObot (and probably make it the default) not to check merge commits. I'm separately requesting that git add a `-s` option to `git merge`. Thanks.

Cc @david-a-wheeler @mkdolan @caniszczyk

**Comment by dankohn** [comment]
Git mailing list reference for the `git merge --signoff` feature request: https://public-inbox.org/git/CAHv71zK5SqbwrBFX=a8-DY9H3KT4FEyMgv__p2gZzNr0WUAPUw@mail.gmail.com/T/#u

**Comment by bkeepers** [comment]
@dankohn thanks for the report. I pushed a change to ignore merge commits for now. Any open PRs will need to be pushed again for the checks to pass.

I'm not opposed to adding a feature in the future to allow people to turn this back on, but it's not currently a priority for me.

**Comment by dankohn** [comment]
Thanks very much. I'm also having a colleague create a patch for git to allow `--signoff` for merge commits. https://public-inbox.org/git/xmqqwp7pl7yh.fsf@gitster.mtv.corp.google.com/T/#t

Separately, I wanted to comment on your blog post: http://opensoul.org/2016/07/03/cii-best-practices/. Note that we already fetch as much info as possible if you use GitHub as your repo, to try to reduce the manual question answering. We call it the BadgeApp, for short, but would be open to alternative names.

We would also greatly appreciate any assistance GitHub could provide in publicizing the project. For, example, we would love a mention on pages like https://opensource.guide/best-practices/ or https://help.github.com/articles/helping-people-contribute-to-your-project/ that projects should get a best practices badge. I'd be happy to discuss further at dan at linuxfoundation.org if you might be interested.

**Comment by david-a-wheeler** [comment]
Thank you so much!!
