### ISSUE TITLE
DCO check fails - commit looks ok

### ISSUE THREAD

**Issue by planetf1** [probot/dco#134]
In https://github.com/odpi/egeriaq we use the DCO bot.

We have a PR https://github.com/odpi/egeria/pull/3386 (actually a merge from a feature branch) that is failing a DCO check on an old commit, and can't understand why.

DCO reports:

```
DCO

You only have one commit incorrectly signed off! To fix, first ensure you have a local copy of your branch by checking out the pull request locally via command line. Next, head to your local branch and run:

git commit --amend --signoff
Now your commits will have your sign off. Next run

git push --force-with-lease origin egeria-feature-openlineage
Commit sha: 2e0dec1, Author: Daniela Otelea, Committer: GitHub; Can not find "Daniela Otelea danielaotelea@users.noreply.github.com", in ["Daniela Otelea daniela-valentina.otelea@ing.com", "Daniela Otelea daniela-valentina.otelea@ing.com", "Daniela Otelea daniela-valentina.otelea@ing.com", "Daniela Otelea daniela-valentina.otelea@ing.com", "Daniela Otelea daniela-valentina.otelea@ing.com", "Daniela Otelea daniela-valentina.otelea@ing.com", "Daniela Otelea daniela-valentina.otelea@ing.com"].
```
Yet when I look at commit 2e0dec1 ie https://github.com/odpi/egeria/pull/3386/commits/2e0dec14f318467f849bfad69a772efd07e15178 I see:
```
Egeria feature openlineage (#3078)
* Asset Lineage OMAS - small refactoring

Signed-off-by: Daniela Otelea <daniela-valentina.otelea@ing.com>

* avoid NPE

Signed-off-by: Daniela Otelea <daniela-valentina.otelea@ing.com>

* delete unused constant

Signed-off-by: Daniela Otelea <daniela-valentina.otelea@ing.com>

* classifications handler changes

Signed-off-by: Daniela Otelea <daniela-valentina.otelea@ing.com>

* Schema Attribute is an entity types

Signed-off-by: Daniela Otelea <daniela-valentina.otelea@ing.com>

* ComplexSchemaTypes is an entity type

Signed-off-by: Daniela Otelea <daniela-valentina.otelea@ing.com>

* Relationship events should be consumed only if at least one end of the relationship is important from lineage

Signed-off-by: Daniela Otelea <daniela-valentina.otelea@ing.com>
```
It has multiple signoffs but I don't understand why the check fails - in all cases the address is correct.

is DCO incorrectly failing the check?

**Comment by gr2m** [comment]
I'm not 100% sure, I'm not very familiar with the implementation. 

From the error message it looks like DCO is explicitly looking for the email address `danielaotelea@users.noreply.github.com`, while the sign offs use `daniela-valentina.otelea@ing.com`. My guess is that because `@danielaotelea` made her email private, DCO cannot know about `daniela-valentina.otelea@ing.com`.

**Comment by planetf1** [comment]
thanks. That makes sense. I'll verify with the author.

**Comment by hiimbex** [comment]
@gr2m is absolutely correct, and since the user's email is private there's nothing we can do on our end to get that data.

Going to close since this is expected behavior.
