### ISSUE TITLE
DCO inconsistency in reformatted part

### ISSUE THREAD

**Issue by Joachim16** [probot/dco#136]
in the original [DCO](https://developercertificate.org/) items a developer certifies are numerated as
(a) (b) (c) (d)
in probot's reformatted for readability version numeration has changed to 1. 2. 3. 4. 
the problem arises under 3. where the reformatting wasn't pulled through.
it reads:
3. The contribution was provided directly to me by some other person who certified **(a), (b) or (c)** and I have not modified it.
**(a), (b) or (c)** actually refers to 1. 2. 3.
best solution for legal consistency: stick with (a) (b) (c) (d) numeration of the original DCO

**Comment by gr2m** [comment]
Hey I'm sorry I cannot follow. Can you elaborate what you mean with

> In probot's reformatted for readability version numeration has changed to 1. 2. 3. 4

**Comment by Joachim16** [comment]
Hi, this is the page I'm referring to: [DCO](https://github.com/apps/dco)

**Comment by gr2m** [comment]
Thank you, I fixed it now
