### ISSUE TITLE
Add the `--no-edit` option for ammending a commit

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [probot/dco#144]
Hi,

what do you think about changing
![image](https://user-images.githubusercontent.com/56065213/103277979-9f506680-49ca-11eb-9d1d-4861f96da996.png)

to

```
git commit --amend --signoff --no-edit
```

to prevent a new editor window poping up?

**Comment by gr2m** [comment]
I think it's a very good idea! Would you like to send a pull request?

**Comment by christian-kreuzberger-dtx** [comment]
Sure, will do!
