### ISSUE TITLE
Hung up on 'Expected — Waiting for status to be reported'

### ISSUE THREAD

**Issue by jmertic** [probot/dco#148]
See this PR...

https://github.com/ambitus/zos-native/pull/2

Note that this was happening before on the same branch and had them close the PR and reopen it...

https://github.com/ambitus/zos-native/pull/1

**Comment by gr2m** [comment]
I checked if we had any errors reported the @ambitus org but no luck and I don't think we keep any logs for the dco app right now. I haven't setup the deployment myself. Maybe @hiimbex knows?
