### ISSUE TITLE
Mysterious DCO probot failure

### ISSUE THREAD

**Issue by jsquyres** [probot/dco#17]
We are using the DCO probot on the ofiwg/libfabric Github project (thanks for this plugin!).  We currently have a custom github webhook plugin that does the same thing as the DCO probot, but would love to ditch it in favor of the DCO probot.  Currently, we are running both of them until we're happy with the DCO probot -- and then we'll turn off our custom hook.

On https://github.com/ofiwg/fabtests/pull/689, the DCO probot returned a failure, but our Signed-off-by-checker returned a success.  Visually inspecting every commit, it looks like every one of them is signed off properly.  We're not quite sure why the DCO probot failed.

Looking at https://github.com/probot/dco/blob/master/lib/dco.js#L7, I'm wondering if the DCO probot failed because the commit author was:

```
Author: Neil Spruit <neil.r.spruit@intel.com>
```

But the signed off line was:

```
Signed-off-by: nrspruit <neil.r.spruit@intel.com>
```

Is the DCO probot failing because the names don't match between the two?

FYI: @shefty @nrspruit

**Comment by bkeepers** [comment]
> Is the DCO probot failing because the names don't match between the two?

That appears to be the case.

I can't find any docs anywhere specifying the correct behavior. `git commit --sign-off` uses the author name from the commit. The [linux kernel docs on the DCO](https://github.com/torvalds/linux/blob/master/Documentation/process/submitting-patches.rst#developers-certificate-of-origin-11) say "…using your real name (sorry, no pseudonyms or anonymous contributions.)"

I'm happy to adjust the behavior of this plugin to match the established norms.

**Comment by jsquyres** [comment]
@bkeepers Thanks for the answer!

Nah, I think we're fine with the current behavior.  It just caused some confusion on our end because the developer *thought* they had signed off on it properly.

Is there a way to indicate *why* the DCO fails, perchance?  I.e., not having a DCO is a pretty obvious  fail.  But if it fails because the DCO is *present but incorrect*, some kind of hint about *what* was incorrect would be awesome.

**Comment by bkeepers** [comment]
> Is there a way to indicate why the DCO fails, perchance? I.e., not having a DCO is a pretty obvious fail. But if it fails because the DCO is present but incorrect, some kind of hint about what was incorrect would be awesome.

Good idea. I opened an issue to document what would need to change. It's not a priority for me right now, but I'm happy to review any Pull Requests that add it: https://github.com/probot/dco/issues/18
