### ISSUE TITLE
Skip check for commits from bots

### ISSUE THREAD

**Issue by bkeepers** [probot/dco#21]
https://github.com/probot/dco/pull/20 has a commit from a bot, which fails the DCO check. Any commit where the author name includes `[bot]` should be ignored.

**Comment by hiimbex** [comment]
Also similar scenario where the bot is an OAuth actor? I assume the problem would be the same there.

cc/ @tbarn

**Comment by charlike** [comment]
Hm. Good point.

**Comment by charlike** [comment]
I think one check in `lib/dco.js` for

```
(commit.author.type === 'Bot' && commit.author.login.endsWith('[bot]')) ||
(commit.commiter.type === 'Bot' && commit.commiter.login.endsWith('[bot]'))
```

would be enough

**Comment by hiimbex** [comment]
sounds about right to me! Wanna open a PR for that @charlike?

**Comment by charlike** [comment]
Yea, i'll give it a shot when have a bit more time :)
