### ISSUE TITLE
provide the commit hashcode on failure

### ISSUE THREAD

**Issue by akosyakov** [probot/dco#32]

**Comment by hiimbex** [comment]
I think this will be solved via #27 which will make the `details` link on failure to a simple web UI to show each commit and the cause for failure.

@bkeepers anything I can do to help with that PR?

**Comment by bkeepers** [comment]
So, I was thinking about this more recently and posted an alternative suggestion in #33.

@akosyakov would this work for you?

**Comment by akosyakov** [comment]
yes, the comment with the instruction sounds good to me
