### ISSUE TITLE
sign-offs not from the author

### ISSUE THREAD

**Issue by akosyakov** [probot/dco#37]
The DCO does not require that the sign-off must be from the author, e.g.: https://lkml.org/lkml/2004/5/25/126

Would it be possible not to fail but warn in the case if commits are signed but not by the author?

**Comment by bkeepers** [comment]
> The DCO does not require that the sign-off must be from the author

Interesting, that's not how I read this from https://lkml.org/lkml/2004/5/25/126:

> You should never sign off for somebody else.
>
> You _can_ sign off as yourself, and just add a note of "From xxxx". That's
> what the (b) case is all about (ie "to the best of my knowledge it's
> already under a open-source license").

For a commit that you are authoring, when would it have a sign-off from someone else?

I'd love to get confirmation from a few others that are more familiar with the DCO on what the appropriate behavior is here.

cc @mkdolan @caniszczyk

**Comment by akosyakov** [comment]
Our issue with the casual contributors who fix typos or couple lines of code. It is obvious that their work is based on ours and under our license. At the same time, they rarely will use git to rebase and sign their commits, leaving PRs hanging.

In such cases, I would like to preserve the authorship but at the same time sign with my signature, meaning that I am responsible for license and copyright issues of these changes.

I am also not sure about how the DCO work and would like to hear an advice of an expert for such cases.

As I read the DCO:
- case (a) - I am an author and I sign a work to ensure that it is under a proper license
- case (b) - I am not an author but I check that a work is under a proper license and sign to ensure it
- case (c) - I received an already signed work and I rely on the signature (kind of recursion to establish trust between developers based on signatures)
