### ISSUE TITLE
Distinguish between internal and external pull requests

### ISSUE THREAD

**Issue by pioterj** [probot/dco#48]
We just replaced CLA with DCO and started to use this app for all public [Gradle](https://github.com/gradle) repositories. 

Our primary motivation was to reduce friction for external contributors and automate the process. In our case, the DCO is not legally needed for Gradle employees that sign separate agreements. Internally we tend to submit our own changes through pull requests too. From what I see the choice we have is either to:

- Sign off our own commits 
- Merge internal PRs with failed DCO checks

I was originally thinking that we would just sign off our own commits. However, one of the engineers brought up the point that it would bloat commit messages a bit for something that is not really necessary. The only reason to sign off our own commits would be to make checks done by [probot/dco](https://github.com/probot/dco) pass. 

Ideally, there would be an option to distinguish between external contributions and contributions from the members of given GitHub organization so that the DCO checks can be skipped for the latter.

**Comment by melix** [comment]
Let me add that the reason the DCO is superfluous internally is that we already sign our commits, which are "Verified" by GitHub.

**Comment by mueller-ma** [comment]
I would love to see the ability to disable the check for a single user.

**Comment by dschaper** [comment]
This is great for limiting the signal/noise ratio for organizational commits. We'd like to lead by example though and enforce DCO even on our own members and just allow the bots and integrations to bypass. Is there a possibility to fine-grain the bypass down to user instead of just org?

**Comment by hiimbex** [comment]
I think this feature request should probably be a new issue as it's unrelated. However, we do exclude GitHub App "bot"s: https://github.com/probot/dco/blob/master/lib/dco.js#L15 This does not include any older OAuth applications where you actually have an account you control for the bot.

**Comment by dschaper** [comment]
Thanks Bex, I'll open a new issue then on this.
