### ISSUE TITLE
Compare case-insensitively

### ISSUE THREAD

**Issue by Vampire** [probot/dco#61]
I correctly signed off a commit with `-s`, but the bot complained because my address was not in all lowercase. Please compare case-insensitively.

**Comment by hiimbex** [comment]
Do you have a link to the commit where this happened? I think this should be an easy fix though, just convert them to lowercase before checking. But that's interesting that the data github gave us about the email address had capitals in it.

**Comment by Vampire** [comment]
It does not, the signed-off line has the captials: https://github.com/gradle/gradle/pull/4986/commits/204a8f8138b8ea2571f9e94324a1fea5517e32fb

**Comment by hiimbex** [comment]
Closed via #62 / #65
