### ISSUE TITLE
Improve UX for people who didn't sign off commits properly

### ISSUE THREAD

**Issue by caniszczyk** [probot/dco#71]
When there is a case where a commit isn't signed off, we should link to instructions or give projects the ability to link to instructions on how to do this.

> "I saw that you didn't sign off your commit, do this...". "I saw that you signed off your commit with XXX but the linked account shows your email as YYY"

**Comment by hiimbex** [comment]
👍 would love to reimplement this app using the [Checks API](https://developer.github.com/v3/checks/) and give better feedback that way.
