### ISSUE TITLE
Document  how to override

### ISSUE THREAD

**Issue by david-a-wheeler** [probot/dco#73]
Sometimes PRs do not have a DCO, but you want to accept them anyway. There should be a note in the readme explaining how to override this check in specific PRs.

**Comment by hiimbex** [comment]
When you say "override this check" do you mean allow the PR to be merged while the check is failing? That is usually by default how status checks work on GitHub; however, you can also have [required status checks](https://help.github.com/articles/enabling-required-status-checks/), which would prevent the PR from being merged.

So to override this check, you simply set the DCO as not a required status check and merge when it's failing. Do you think this explanation belongs in the readme?

**Comment by hiimbex** [comment]
Gonna go ahead and close due to lack of response, but if there's follow up, happy to review a PR to add that content to the readme, but right now I don't feel strongly enough to do it.
