### ISSUE TITLE
Read Signed-off-by in pull request text

### ISSUE THREAD

**Issue by DL6ER** [probot/dco#74]
Dear DCO developers,

we use your bot to enforce Sign-Off lines by our users in our project. However, we often receive external contributions from users with few (or no) previous experience with Github and adding a Signed-Off-by message in all of their commits (by walking the tree and rewriting things) is something that is a bit complex to explain to newcomers.

Hence, our own solution was to ask users to just edit in the requested line into the pull request message and we accept this as being equivalent. However, DCO does not read the pull request text for these lines and hence we have to ignore its false positive for merging.

Can interpreting the pull request text be added in order to ease the process for `git` newcomers?

**Comment by hiimbex** [comment]
I'm not opposed to this at all; however, I think some orgs that are stricter in their requiring of DCO might not love this idea, so what about adding this feature as an additional field in the [`.github/dco.yml`](https://github.com/probot/dco#skipping-sign-off-for-organization-members) as `allowPRSignOff: true` (and have it be false by default)?

**Comment by bkeepers** [comment]
I think this would help a lot with usability.

**Comment by DL6ER** [comment]
Yes, this is still relevant.

**Comment by DL6ER** [comment]
Yes, this is still relevant.

**Comment by Warchant** [comment]
Is anyone working on this?

**Comment by itayd** [comment]
Hi, I suggest an alternative solution in https://github.com/probot/dco/issues/105. Feel free to share your thoughts.
