### ISSUE TITLE
Feature requests for DCO integration?

### ISSUE THREAD

**Issue by bkeepers** [probot/dco#8]
Currently, this GitHub Integration will check commits in a Pull Requests to verify that all of them have the DCO sign-off. See #2 for a demo. As the [README documents](https://github.com/probot/dco#usage), you can use require statuses to require that the DCO check passes before allowing a pull request to be merged.

What other features are desired for DCO integration?

cc @mkdolan @caniszczyk

**Comment by bkeepers** [comment]
By the way, feel free to [try this out on own project](http://github.com/integration/dco).

**Comment by bkeepers** [comment]
@mikeal [said](https://twitter.com/mikeal/status/845762137918136320):

> the main feature I would want would be "comment in the PR with instructions on how to add sign-off-by by default"

**Comment by mkdolan** [comment]
@bkeepers awesome! Is it possible to also require signed commits with the sign-off on?

**Comment by bkeepers** [comment]
> @bkeepers awesome! Is it possible to also require signed commits with the sign-off on?

@mkdolan you mean GPG signed? That's a great suggestion. There is a [commit signature verification API](https://developer.github.com/v3/git/commits/#commit-signature-verification), so it should be pretty easy to add an option that commits also be GPG signed.

Would you expect that to be the default for this integration, or is it common for projects to not require GPG signatures?
