### ISSUE TITLE
DCO check passing when there is not a signoff.

### ISSUE THREAD

**Issue by JPWKU** [probot/dco#81]
There seems to be an issue here https://github.com/edgexfoundry/edgex-go/pull/376
where the commit is not signed, but the DCO check still passes.  Perhaps I'm overlooking something?

**Comment by hiimbex** [comment]
This was my bad! Definitely a 🐛🐞 Thanks for reporting it

Opened a PR for the fix #82

**Comment by JPWKU** [comment]
No worries, thanks for responding so quickly!
