### ISSUE TITLE
Checks API Feedback

### ISSUE THREAD

**Issue by hiimbex** [probot/dco#86]
Hello DCO users! 

We recently updated the DCO to utilize the new [checks API](https://developer.github.com/v3/checks/). This means that we can now explain to users more easily how to add their sign-off to commits. We hope you’ll accept this permissions update to make the user experience for DCO users easier. In the meantime, we will be offering backwards compatible support for statuses until permissions are updated. 

Check it out in action [here](https://github.com/probot/test/pull/31/checks?check_run_id=12444418). 

You might notice a new button on that screen if you have WRITE access to a repo using the DCO. That button will automatically set the app's status to passing.

You can learn more about the process we went through to update the app here: https://github.com/probot/dco/pull/79. Feel free to comment any feedback or let us know if you have any questions/concerns or run into any problems.

**Comment by cliveb** [comment]
I received the email, yet the ability to accept and grant new permissions is not enabled (can't push green button). I am an admin on the repo @hiimbex?  

"[GitHub] A GitHub App, DCO, is requesting updated permissions". 

The DCO app by probot is requesting updated permissions

https://github.com/organizations/CertifiedTrue/settings/installations/213902/permissions/update

**Comment by hiimbex** [comment]
Weird you got the email but can't authorize the app! This would be a permissions issue unrelated to the DCO. @cliveb I'd recommend contacting GitHub support if this problem persists!
