### ISSUE TITLE
Rendered version of DCO at https://probot.github.io/apps/dco/ contains unmatched references to (a), (b) and (c)

### ISSUE THREAD

**Issue by tyll** [probot/dco#96]
https://probot.github.io/apps/dco/ says:

```
By making a contribution to this project, I certify that:

1. The contribution was created in whole or in part by me and I have the right to submit it under the open source license indicated in the file; or

2. The contribution is based upon previous work that, to the best of my knowledge, is covered under an appropriate open source license and I have the right under that license to submit that work with modifications, whether created in whole or in part by me, under the same open source license (unless I am permitted to submit under a different license), as indicated in the file; or

3. The contribution was provided directly to me by some other person who certified (a), (b) or (c) and I have not modified it.

4. I understand and agree that this project and the contribution are public and that a record of the contribution (including all personal information I submit with it, including my sign-off) is maintained indefinitely and may be redistributed consistent with this project or the open source license(s) involved.
```

The paragraphs are numbered with 1., 2., 3, and 4. but the refernce in 3. is (a), (b) or (c).

**Comment by tyll** [comment]
It is still wrong at https://probot.github.io/apps/dco/ and it is blocked by me not having write access to the system to change the layout or someone else caring to change it.

**Comment by hiimbex** [comment]
PRs welcome: https://github.com/probot/probot.github.io/blob/master/_apps/dco.md

**Comment by tyll** [comment]
> PRs welcome: https://github.com/probot/probot.github.io/blob/master/_apps/dco.md

@hiimbex what did you mean with "PRs welcome"? I filed the trivial PR 23 days ago and got no feedback so far... IMHO this is not how to welcome PRs.

**Comment by hiimbex** [comment]
I'm no longer at GitHub and their team supporting this probot has shrunken/shifted priorities. I do try to merge DCO things when I can. Sorry for the inconvenience
